[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pyth_example = "n3t6sxhffRkPNs8F7pyWMjwrSEnWmRScFBVwofpYNWj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
